# Generated by Django 5.0.3 on 2024-03-07 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=11)),
                ('message', models.TextField()),
                ('user_address', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.CharField(max_length=30)),
                ('e_description', models.TextField()),
                ('e_image', models.FileField(default='', upload_to='photos')),
                ('calories_burned_per_minute', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=20)),
                ('duration', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired')], max_length=20)),
                ('payment_method', models.CharField(max_length=20)),
                ('amount', models.FloatField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('mobile', models.BigIntegerField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Order_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('placed', 'placed'), ('pending', 'pending'), ('complete', 'complete')], default='', max_length=20)),
                ('amount', models.FloatField()),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.subscriptionplan_table')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='DietChart_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_type', models.CharField(choices=[('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Breakfast', 'Breakfast')], default='Lunch', max_length=20)),
                ('d_name', models.CharField(max_length=50)),
                ('food_name', models.CharField(default='', max_length=20)),
                ('d_image', models.ImageField(default='', upload_to='photos')),
                ('d_description', models.TextField()),
                ('age', models.CharField(choices=[('10-25', '10-25'), ('25-40', '25-40'), ('40-55', '40-55'), ('55-70', '55-70')], default='', max_length=20)),
                ('diseases', models.CharField(choices=[('obesity', 'obesity'), ('cholesterol', 'cholesterol'), ('Heart health', 'Heart health'), ('Acidity', 'Acidity'), ('Blood Pressure', 'Blood Pressure'), ('Diabetes', 'Diabetes'), ('None', 'None')], default='', max_length=30)),
                ('d_created_date', models.DateField(auto_now=True)),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.subscriptionplan_table')),
            ],
        ),
        migrations.CreateModel(
            name='payment_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=10)),
                ('status1', models.CharField(choices=[('placed', 'placed'), ('pending', 'pending'), ('complete', 'complete')], default='', max_length=20)),
                ('time', models.DateTimeField()),
                ('a_amount', models.FloatField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.order_table')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('rating', models.FloatField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.CharField(max_length=30)),
                ('comment', models.CharField(default='', max_length=300)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(choices=[('10-25', '10-25'), ('25-40', '25-40'), ('40-55', '40-55'), ('55-70', '55-70')], max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('dieseas', models.CharField(choices=[('obesity', 'obesity'), ('cholesterol', 'cholesterol'), ('Heart health', 'Heart health'), ('Acidity', 'Acidity'), ('Blood Pressure', 'Blood Pressure'), ('Diabetes', 'Diabetes'), ('None', 'None')], max_length=30)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='Card_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=30)),
                ('card_number', models.CharField(default='', max_length=16)),
                ('cvv', models.IntegerField()),
                ('card_expiry_date', models.CharField(default='', max_length=20)),
                ('card_balance', models.FloatField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.user_table')),
            ],
        ),
    ]
