# Generated by Django 5.0.3 on 2024-03-07 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback_table',
        ),
    ]
