# Generated by Django 5.0.3 on 2024-04-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0002_delete_feedback_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan_table',
            name='desc',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
